### ISSUE TITLE
--reporter-json-summary-export does not work together with standard JSON reporter

### ISSUE THREAD

**Issue by csvan** [spenceclark/newman-reporter-json-summary#1]
If I run this reporter by itself or together with another reporter (e.g. `-r html,json-summary`), the `--reporter-json-summary-export` flag is respected and the JSON file is generated where I request it.

However, if I run it with the standard json reporter (`-r json,json-summary`), both JSON files are generated correctly, *but*, the json-summary file ends up under the default `newman` folder, and custom file names are not respected.

**Comment by spenceclark** [comment]
Hi. I've fixed this issue now - latest version (1.0.11) has been published to NPM

**Comment by Duckbringer** [comment]
> Hi. I've fixed this issue now - latest version (1.0.11) has been published to NPM

I run the reporter together with htmlextra and experiance the same issue, newman folder is created and results end up there
