### ISSUE TITLE
.git folder in latest npm package 1.0.11

### ISSUE THREAD

**Issue by davepile** [spenceclark/newman-reporter-json-summary#3]
I installed newman-reporter-json-summary locally and then was unable to install newman-reporter-html in the same project as I got an npm error EISGIT
EISGIT
npm ERR! git ...\postman\testrunner\node_modules\newman-reporter-json-summary: Appears to be a git repo or submodule.
npm ERR! git     ...\postman\testrunner\node_modules\newman-reporter-json-summary

I had to manually remove the .git folder from node_modules\newman-reporter-json-summary

**Comment by spenceclark** [comment]
Strange, not sure how that happened. I've updated the .gitignore file and republished and i can now upgrade and remove the package without that error. Hopefully thats fixed it.

**Comment by spenceclark** [comment]
Fixed
