### ISSUE TITLE
reporter-json-summary-export is not creating output file

### ISSUE THREAD

**Issue by Lsiriki** [spenceclark/newman-reporter-json-summary#4]
newman run collection -r json-summary,cli --reporter-json-summary-export output is not generating the output json file with 1.0.11 version. Its working on 1.0.10.

**Comment by spenceclark** [comment]
Hi, the parameter name has changed in version 1.0.11 as the old version caused a clash when combined with the default JSON reporter. I've just updated the readme.md

Its now --reporter-**summary-json**-export

**Comment by Lsiriki** [comment]
With parameter --reporter-summary-json-export its creating the output json file now. Thanks.
